server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Rutas de Flutter web (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Compresión
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
}
